const styles = {
	"vanta-auth-close": `[position:absolute] [top:14px] [right:14px] [z-index:2] [width:34px] [height:34px] [display:grid] [place-items:center] [border:1px_solid_var(--vanta-border)] [border-radius:50%] [background:var(--vanta-surface)] [color:var(--vanta-text)] [transition:.18s_ease] hover:[border-color:var(--vanta-text)] hover:[transform:rotate(4deg)]`,
	"vanta-auth-content": `[padding:38px_36px_28px] max-[640px]:[padding:34px_22px_24px]`,
	"vanta-auth-divider": `[margin:22px_0_14px] [display:flex] [align-items:center] [gap:10px] [color:var(--vanta-muted)] [font-size:8px] [white-space:nowrap] [&::before]:[content:""] [&::before]:[height:1px] [&::before]:[flex:1] [&::before]:[background:var(--vanta-border)] [&::after]:[content:""] [&::after]:[height:1px] [&::after]:[flex:1] [&::after]:[background:var(--vanta-border)]`,
	"vanta-auth-error": `[margin-top:17px] [padding:10px_12px] [border:1px_solid_rgba(177,_57,_57,_.28)] [background:rgba(177,_57,_57,_.06)] [color:#9e3333] [font-size:9px] [line-height:1.5]`,
	"vanta-auth-field": `[display:block] [margin-top:15px] first-child:[margin-top:0] [&>span]:[display:block] [&>span]:[margin-bottom:7px] [&>span]:[color:var(--vanta-text)] [&>span]:[font-size:8px] [&>span]:[font-weight:700] [&>span]:[letter-spacing:.08em] [&>span]:[text-transform:uppercase]`,
	"vanta-auth-form": `[margin-top:24px]`,
	"vanta-auth-heading": `[padding-right:32px] [&h2]:[margin:0] [&h2]:[font-family:"Playfair_Display",_Georgia,_serif] [&h2]:[font-size:32px] [&h2]:[line-height:1] [&h2]:[font-weight:600] [&h2]:[letter-spacing:-.025em] [&p:not(.vanta-auth-kicker)]:[margin:22px_0_0] [&p:not(.vanta-auth-kicker)]:[font-size:13px] [&p:not(.vanta-auth-kicker)]:[font-weight:600] [&small]:[display:block] [&small]:[margin-top:6px] [&small]:[color:var(--vanta-muted)] [&small]:[font-size:9px] [&small]:[line-height:1.5]`,
	"vanta-auth-input-wrap": `[height:42px] [display:flex] [align-items:center] [gap:9px] [padding:0_11px] [border:1px_solid_var(--vanta-border)] [background:var(--vanta-surface)] [color:var(--vanta-muted)] [transition:border-color_.18s_ease,_box-shadow_.18s_ease] focus-within:[border-color:var(--vanta-text)] focus-within:[box-shadow:0_0_0_1px_var(--vanta-text)] [&input]:[width:100%] [&input]:[min-width:0] [&input]:[height:100%] [&input]:[border:0] [&input]:[outline:0] [&input]:[padding:0] [&input]:[background:transparent] [&input]:[color:var(--vanta-text)] [&input]:[font-size:10px] [&input::placeholder]:[color:#aaa79f]`,
	"vanta-auth-kicker": `[margin:0_0_18px] [color:var(--vanta-muted)] [font-size:8px] [font-weight:700] [letter-spacing:.26em]`,
	"vanta-auth-link-button": `[border:0] [background:transparent] [color:var(--vanta-muted)] [padding:0] [font-size:8px] [text-decoration:underline] [text-underline-offset:2px]`,
	"vanta-auth-modal": `[position:relative] [width:min(100%,_430px)] [max-height:min(92vh,_720px)] [overflow-y:auto] [background:var(--vanta-surface)] [color:var(--vanta-text)] [border:1px_solid_rgba(17,_17,_17,_.12)] [box-shadow:0_28px_80px_rgba(0,_0,_0,_.28)] [animation:vanta-auth-pop_.22s_cubic-bezier(.2,_.8,_.2,_1)_both] max-[640px]:[width:100%] max-[640px]:[max-height:94vh] max-[640px]:[border-right:0] max-[640px]:[border-bottom:0]`,
	"vanta-auth-options": `[margin-top:13px] [display:flex] [align-items:center] [justify-content:space-between] [gap:12px]`,
	"vanta-auth-overlay": `[position:fixed] [inset:0] [z-index:100] [display:flex] [align-items:center] [justify-content:center] [padding:22px] [background:rgba(8,_9,_9,_.58)] [backdrop-filter:blur(8px)] [-webkit-backdrop-filter:blur(8px)] [animation:vanta-auth-fade_.18s_ease_both] max-[640px]:[align-items:flex-end] max-[640px]:[padding:0]`,
	"vanta-auth-password-toggle": `[width:24px] [height:24px] [flex:0_0_24px] [display:grid] [place-items:center] [border:0] [background:transparent] [color:var(--vanta-muted)]`,
	"vanta-auth-remember": `[display:inline-flex] [align-items:center] [gap:6px] [color:var(--vanta-muted)] [font-size:8px] [&input]:[width:12px] [&input]:[height:12px] [&input]:[margin:0] [&input]:[accent-color:var(--vanta-text)]`,
	"vanta-auth-socials": `[display:grid] [grid-template-columns:repeat(3,_1fr)] [gap:8px] [&span]:[height:36px] [&span]:[display:grid] [&span]:[place-items:center] [&span]:[border:1px_solid_var(--vanta-border)] [&span]:[color:var(--vanta-text)] [&span]:[font-size:12px] [&span]:[font-weight:700]`,
	"vanta-auth-submit": `[width:100%] [min-height:44px] [margin-top:17px] [border:1px_solid_var(--vanta-text)] [background:#111313] [color:#fff] [font-size:9px] [font-weight:700] [letter-spacing:.14em] [text-transform:uppercase] [transition:.18s_ease] hover:[transform:translateY(-1px)] hover:[opacity:.9] disabled:[cursor:wait] disabled:[opacity:.55]`,
	"vanta-auth-switch": `[margin:19px_0_0] [text-align:center] [color:var(--vanta-muted)] [font-size:8px] [&button]:[border:0] [&button]:[padding:0] [&button]:[background:transparent] [&button]:[color:var(--vanta-text)] [&button]:[font-weight:700] [&button]:[text-decoration:underline] [&button]:[text-underline-offset:2px]`,
	"vanta-login-input": `[color:var(--vanta-text)] [background:var(--vanta-surface)] focus:[box-shadow:0_0_0_1px_var(--vanta-text)]`,
	"vanta-login-modal": `[color:var(--vanta-text)] [background:var(--vanta-surface)] max-[640px]:[min-height:100%]`,
};

export default styles;
