const styles = {
	"vanta-review-card": `[border:1px_solid_var(--vanta-border)] [background:var(--vanta-surface)] [padding:20px] [&h3]:[margin:11px_0_0] [&h3]:[font-size:13px] [&p]:[margin:8px_0_0] [&p]:[color:var(--vanta-muted)] [&p]:[font-size:11px] [&p]:[line-height:1.7] [&small]:[display:block] [&small]:[margin-top:14px] [&small]:[color:var(--vanta-muted)] [&small]:[font-size:8px] [&small]:[text-transform:uppercase] [&small]:[letter-spacing:.14em]`,
	"vanta-review-form": `[margin-top:28px] [border:1px_solid_var(--vanta-border)] [background:var(--vanta-surface)] [padding:24px] [&input]:[width:100%] [&input]:[border:1px_solid_var(--vanta-border)] [&input]:[background:var(--vanta-bg)] [&input]:[color:var(--vanta-text)] [&input]:[outline:none] [&input]:[padding:0_12px] [&input]:[font-size:11px] [&select]:[width:100%] [&select]:[border:1px_solid_var(--vanta-border)] [&select]:[background:var(--vanta-bg)] [&select]:[color:var(--vanta-text)] [&select]:[outline:none] [&select]:[padding:0_12px] [&select]:[font-size:11px] [&textarea]:[width:100%] [&textarea]:[border:1px_solid_var(--vanta-border)] [&textarea]:[background:var(--vanta-bg)] [&textarea]:[color:var(--vanta-text)] [&textarea]:[outline:none] [&textarea]:[padding:0_12px] [&textarea]:[font-size:11px] [&input]:[height:42px] [&select]:[height:42px] [&textarea]:[min-height:110px] [&textarea]:[margin-top:10px] [&textarea]:[padding-top:12px] [&textarea]:[resize:vertical] [&>button]:[margin-top:10px] [&>button]:[border:0] [&>button]:[background:#111313] [&>button]:[color:#fff] [&>button]:[padding:12px_18px] [&>button]:[font-size:9px] [&>button]:[font-weight:700] [&>button]:[letter-spacing:.12em] [&>button]:[text-transform:uppercase]`,
	"vanta-review-form-grid": `[display:grid] [grid-template-columns:180px_1fr] [gap:10px] [margin-top:15px] max-[700px]:[grid-template-columns:1fr]`,
	"vanta-review-grid": `[display:grid] [grid-template-columns:repeat(2,_1fr)] [gap:12px] [margin-top:28px] max-[700px]:[grid-template-columns:1fr]`,
	"vanta-review-summary": `[display:flex] [align-items:center] [gap:10px] [font-size:10px] [color:var(--vanta-muted)]`,
	"vanta-reviews-section": `[max-width:1184px] [margin:66px_auto_0] [padding:0_28px] max-[700px]:[padding:0_18px]`,
};

export default styles;
